# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
    
  ui_lint_test:
    name: Run ui test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Yarn Install & Cache Dependencies
      uses: bahmutov/npm-install@v1.4.5

    - run: yarn test:unit
      env:
        CI: true
